pkg/agent/agent.go
pkg/manager/manifests/templates/work-clusterrole.yaml
pkg/manager/manifests/templates/work-clusterrolebinding.yaml
pkg/util/constant.go

make sure the hub client is set up correctly

---

pkg/agent/agent.go

watch hostedcluster owned by appliedmanifestwork and sync secret to hub

---

sonar-project.properties

Add sonar properties

---

Dockerfile

Change user for the Dockerfile

---

example/addon-manager-deployment.yaml

limit rbac for manager within the sample

---

pkg/agent/agent.go

- Add target namespace info to the hub mirror secret name, otherwise, the secret name may conflict if there are two hypershiftDeployment with different namespace and different spec.TargetNamespace but with the same name.
- Add annotation to record hypershift deployment ns/name to the hubMirrorSecret

Add target namespace info to the hub mirror secret name

---

pkg/agent/agent.go

Change hypershift deployment annotation name

---

Dockerfile

remove extra PATH setting

---

Makefile

split the make build for downstream

---

example/hypeshift-imagestream.yaml

add configmap sample

---

pkg/agent/agent.go

After https://github.com/stolostron/hypershift-deployment-controller/pull/48 is merged, we create the manifestwork with delete option `orphan`, which will lead to the hosted cluster without appliedmanifestwork owner reference. So we use the annotation to replace the owner reference to filter the hosted cluster.

Filter hosted cluster by annotation

---

go.mod
pkg/agent/agent.go
pkg/agent/clusterclaim.go
pkg/agent/clusterclaim_test.go
pkg/util/constant.go

issue reference: https://github.com/stolostron/backlog/issues/20056
Will use https://github.com/stolostron/backlog/issues/21241 to trace the permission problem.

Add cluster claim for hypershift clusters

---

README.md

trigger CI

---

pkg/agent/hypershift.go

Signed-off-by: xuezhaojun <zxue@redhat.com>

Fix: using spokeClient in deploymentExist

---

pkg/manager/manifests/templates/clusterrole.yaml
pkg/manager/manifests/templates/clusterrolebinding.yaml

Signed-off-by: xuezhaojun <zxue@redhat.com>

Add permissions for operator

---

Makefile
example/addon-manager-deployment.yaml
go.mod
go.sum
pkg/agent/hypershift.go
pkg/util/constant.go
test/e2e/e2e_suite_test.go
test/e2e/install_test.go
test/e2e/util/util.go

issue reference: https://github.com/stolostron/backlog/issues/20421
TODO:

Add e2e tests

---

Makefile
hack/install_ocm.sh

Fix e2e issue

---

pkg/manager/manifests/templates/deployment.yaml

* remove the extra blank
*  fix typo
* https://github.com/stolostron/hypershift-addon-operator/pull/40#pullrequestreview-965323572
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	0.031s	coverage: 6.0% of statements
```

fix typo remove the extra blank

---

pkg/agent/agent.go

* Add support for CUSTOM ManagedCluster names
* Support the original ManagedCluster.Name = HostedCluster.Spec.InfraId (ServiceDelivery & BM Agent UI)
* Support HypershiftDeployment creates ManagedCluster with HypershiftDeployment.Name
* Make sure not to affect BareMetal Agent and ServiceDelivery with this change
* This fixes bugzilla 2114008 which shows two copies of the cluster in the 2.6 UI
*  Currently the UI is broken on Azure and AWS hypershift deployments where you will see two copies.
* https://github.com/stolostron/backlog/issues/24783
* https://bugzilla.redhat.com/show_bug.cgi?id=2114008
```script
PASS
coverage: 71.5% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	13.263s	coverage: 71.5% of statements …
```

Add support for CUSTOM ManagedCluster names

---

pkg/agent/hypershift.go
pkg/agent/hypershift_test.go

* The deletion of the HyperShift addon operator is enhanced to check if there are existing Hosted Clusters. Only delete the HyperShift operator if there are no Hosted Clusters
*  Deleting the HyperShift addon operator if there are existing Hosted Clusters will leave the HCs orphaned and difficult to clean up.
* https://issues.redhat.com/browse/ACM-1583
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	3.516s	coverage: 72.2% of statements
```

Do not delete HS operator when deleting HS addon if there are HCs

---

docs/upgrading_hypershift_operator.md

* Describe how to upgrade hypershift operator using a configmap and manifestwork
*  For users that need to upgrade hypershift operator on hosting cluster in between MCE releases
* https://issues.redhat.com/browse/ACM-1648
```script
```

Hypershift operator image upgrade doc

---

docs/upgrading_hypershift_operator.md

* Fixed the configmap examples in the image upgrade doc
*  
* 
```script
```

fix configmap example

---

docs/provision_hosted_cluster_on_mce_local_cluster.md
docs/provision_hypershift_clusters_by_manifestwork.md
quickstart/README.md
quickstart/acm-start.sh
quickstart/create-policy.sh
quickstart/create-s3-bucket.sh
quickstart/mce-start.sh

* Add Scripts from hypershift-deployment repo.
* Add Mark Down documents related to SD
*  Consolidate tools and documentation
* https://issues.redhat.com/browse/ACM-1831
```script
NA
```

Add documentation and Scripts

---

docs/installing_hypershift_cli.md

* Provide CLI binaries for users until official ones are available elsewhere
* Document how to install the CLI
*  
* 
```script
```

add CLI binaries and doc

---

docs/provision_hosted_cluster_on_mce_local_cluster.md

* fix doc error for hypershift hosted cluster on mce
*  doc error, managercluster cr yaml format error
* 
```script
```

fix doc error for hypershift hosted cluster on mce

---

docs/provision_hosted_cluster_on_mce_local_cluster.md

* The external DNS document is not consistent with the code implementation or the upstream hypershift doc https://hypershift-docs.netlify.app/how-to/external-dns. 
*  Correct document
* https://issues.redhat.com/browse/ACM-2052
```script
```

ACM-2052: fix the external DNS doc

---

docs/provision_hosted_cluster_on_mce_local_cluster.md

Signed-off-by: David Huynh <dhuynh@redhat.com>
* Update doc to reflect:
* hypershift-addon auto-installed when turning on hypershift feature
* move step for creating s3 secret to before turning on feature 
* added some unsupported notes/workarounds 
*  Hypershift-addon will now automatically be enabled on local-cluster as per ACM-1754 once feature is enabled on MCE, no need to add step for it but can reference the needed YAML to do it
* https://issues.redhat.com/browse/ACM-1754
```script
```

ACM-1754: enable hypershift-addon on local-cluster automatically

---

docs/scheduling_hosted_cluster.md

* Add more samples for AddOnPlacementScore
*  
* 
```script
```

add more doc on AddOnPlacementScore

---

docs/hypershift_addon_status.md

* Add a doc to explain the hypershift addon status in details.
*  Assist hypershift addon users with status monitoring
* No issue, as requested by team lead.
```script
Not applicable
```

Add a doc to explain the hypershift addon status in details.

---

pkg/manager/cli_download_install.go
pkg/manager/cli_download_install_test.go

* Start with lower case character in internal function names
*  
* 
```script
```

fix function names

---

docs/running_mce_acm_addons_hostedmode.md

* Verified and added doc on how to enable addons in hosted mode
*  Run addons in hosted mode
* https://issues.redhat.com/browse/ACM-2307
```script
```

add hosted mode addons doc

---

docs/installing_hypershift_cli.md
pkg/manager/cli_download_install.go
pkg/manager/manifests/templates/deployment.yaml

* Update CLI download path for consistent file name and instructions
* Update the doc
*  
* 
```script
```

update CLI download paths and doc

---

quickstart/README.md
quickstart/acm-start.sh
quickstart/mce-start.sh

Signed-off-by: David Huynh <dhuynh@redhat.com>
* update quickstart scripts to reflect latest changes
*  
* https://issues.redhat.com/browse/ACM-1754
```script
```

update quickstart scipts

---

docs/enable_hypershift_operator_RHOBS.md
pkg/install/hypershift.go
pkg/install/hypershift_test.go
pkg/install/install_job.go
pkg/manager/manifests/templates/deployment.yaml

* Enable RHOBS monitoring for hypershift
*  
* https://issues.redhat.com/browse/HOSTEDCP-675
```script
```

enable RHOBS monitoring for hypershift

---

docs/provision_hosted_cluster_on_mce_local_cluster.md

* Add a link to the hypershift addon status checking doc
*  Better doc
* 
```script
```

add link to the addon status check doc

---

docs/provision_hosted_cluster_on_mce_local_cluster.md

* Documentation on how to add node selector and tolerations to the HyperShift addon
*  User may want the addon to run in the infrastructure node
* https://issues.redhat.com/browse/ACM-2402
```script
```

Add doc on how to config hypershift addon to run in infra node

---

OWNERS

* Add mikeshng to OWNERS file
*  Might help with openshift/release approval
* not applicable
```script
not applicable
```

Add mikeshng to OWNERS file

---

pkg/metrics/hosted-clusters-metrics.go

* Expose `mce_hs_addon_available_hosted_control_planes_gaug` metric
*  
* https://issues.redhat.com/browse/ACM-3069
```script
```

expose a metric

---

pkg/agent/agent.go
pkg/agent/agent_test.go

* In the admin-kubeconfig on the hub, replace the certificate-authority-data with the naming cert provided by the user in the hosted cluster, if it exists.
*  In the admin-kubeconfig, the certifcate-authority-data contains the self-signed root CA instead or the naming cert provided by the user.
* https://issues.redhat.com/browse/ACM-3990
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	20.392s	coverage: 72.5% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	281.033s	coverage: 87.0% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/manager	1.214s	coverage: 55.8% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/metrics	0.748s	coverage: 100.0% of statements
```

Replace ca cert in admin-kubeconfig

---

docs/advanced/backup_restore.md

* Backup and restore documentation for SD
*  
* 
```script
```

Backup and restore documentation

---

docs/advanced/backup_restore.md

* Update backup/restore doc
*  
* 
```script
```

update BR doc

---

docs/hypershift_operator_configuration.md
docs/provision_hosted_cluster_on_mce_local_cluster.md

* Add HO configuration doc for disconnected environment
*  Support disconnected env
* https://issues.redhat.com/browse/ACM-3981
```script
```

add doc on disconnected env

---

docs/hcp_resource_minimum_reqs.md

* Document the minimum resource requirements for a hosted control plane
*  
* https://issues.redhat.com/browse/ACM-3343
```script
```

document minimum HCP resource requirements

---

docs/hcp_resource_minimum_reqs.md

* Update the minimum required HCP PV sizes
*  
* 
```script
```

update minimum requirement PV sizes

---

docs/provision_hosted_cluster_on_mce_local_cluster.md

* Update the S3 bucket creation doc (https://github.com/openshift/hypershift/pull/2461)
*  
* 
```script
```

update s3 bucket creation doc

---

docs/hcp_disaster_recovery.md

* Add a reference to OCP doc on how to recover hosted control planes from disaster.
* Currently there is no backup and restore feature in MCE so I decided not to document the process of recovering the managed cluster portion of a hosted cluster.
*  
* https://issues.redhat.com/browse/ACM-4267
```script
```

add hosted cluster DR doc

---

docs/provision_hosted_cluster_on_mce_local_cluster.md

* Update AWS creation doc 
*  
* 
```script
```

update AWS doc

---

pkg/agent/external_secret_controller.go

* Cherry-pick https://github.com/stolostron/hypershift-addon-operator/pull/243
*  
* https://issues.redhat.com/browse/ACM-5826
```script
```

Use Patch instead of Update for HostedCluster Objects (#243)

---

docs/hypershift_operator_configuration.md

* Document external-dns image installation flag.
*  Document external-dns image installation flag.
* [HOSTEDCP-1009](https://issues.redhat.com/browse/HOSTEDCP-1009)
```script
```

Document external-dns image installation flag

---

docs/advanced/provision_hypershift_clusters_by_manifestwork.md
docs/provision_hosted_cluster_on_mce_local_cluster.md
pkg/agent/agent.go
pkg/util/constant.go
test/canary/resources/hosted_cluster_manifestwork.yaml

* Update the SD doc to describe the correct set of managed cluster annotations
*  Getting the doc up to date
* https://issues.redhat.com/browse/ACM-5844
```script
```

ACM-5844 update doc

---

docs/provision_hosted_cluster_on_mce_local_cluster.md

* Remove unused annotation, some lint cleanup
*  
* 
```script
```

remove unused annotation

---

docs/provision_hosted_cluster_on_mce_local_cluster.md

* https://issues.redhat.com/browse/ACM-6496
* https://issues.redhat.com/browse/ACM-1659
* small update to include patch cmd to update config
*  
* 
```script
```

ACM-6496 & ACM-1659: remove hypershift-preview & add alternative command to patch addondeploymentconfig

---

docs/hosting_cluster_topologies.md
docs/hypershift_operator_configuration.md

* Document possible MCE hosting cluster topologies
*  
* 
```script
```

Document possible hosting cluster topologies

---

pkg/agent/agent.go
pkg/agent/agent_test.go
pkg/agent/hcp_capacity_calculation.go
pkg/agent/hcp_capacity_calculation_test.go
pkg/metrics/hcp-size-calculation-metrics.go
pkg/metrics/hosted-clusters-metrics.go

* Adding more metrics about hosted control planes
*  We need more metrics to build insightful dashboards
* https://issues.redhat.com/browse/ACM-9017
```script
```

ACM-9017: Add more metrics about HCP

---

docs/hosting_cluster_topologies.md

* Document how to import MCE clusters into ACM for hosting clusters in MCE clusters.
*  Document more examples of hosting hosted clusters using MCE and managing them via ACM.
* 
```script
```

Document hosting cluster topology with MCE as hosting clusters

---

docs/advanced/backup_restore.md

* Add the HCP backup/restore doc link
*  
* 
```script
```

update the b/r doc

---

docs/discovering_hostedclusters.md

* This documents the end-to-end flow of Epic https://issues.redhat.com/browse/ACM-11041
*  
* https://issues.redhat.com/browse/ACM-11041
```script
```

ACM-11041: Documentation

---

docs/discovering_hostedclusters.md

* Added a section about detaching.
*  
* 
```script
```

More discovery doc

---

sonar-project.properties

add sonar exclusion

---

pkg/manager/manifests/cli/deployment.yaml

* The memory resource limit is too low
*  To fix OOM during a performance test
* https://issues.redhat.com/browse/ACM-11770
```script
```

ACM-11770: Increase memory for hcp cli download pod

---

pkg/agent/agent.go

* Some Sonar security scan problems are fixed
*  To pass Sonar quality gate
* 
```script
```

sonar gosec fix

---

docs/discovering_hostedclusters.md

* Adding missing steps for MCE HCP discovery 
*  
* 
```script
```

Add missing discovery doc steps

---

Dockerfile.rhtap

* Fixed Dockerfile.rhtap
*  
* 
```script
```

Dockerfile.rhtap fix

---

docs/discovering_hostedclusters.md

ACM-12103: Policy fix

---

docs/discovering_hostedclusters.md

* Add more doc on detaching discovered clusters.
*  
* 
```script
```

Doc to deatch discovered clusters

---

docs/discovering_hostedclusters.md

* Document MCE-hcp discovery limitations
*  
* 
```script
```

Document MCE-hcp discovery limitations

---

docs/discovering_hostedclusters.md
pkg/agent/external_secret_controller.go
pkg/agent/external_secret_controller_test.go

* Filter out irrelevant klusterlets on external secret reconciliation
*  
* 
```script
```

Optimize external secret controller

---

pkg/manager/manifests/templates/clusterrole.yaml

ACM-12304 for 2.5

---

Makefile
pkg/manager/manifests/templates/clusterrole.yaml

ACM-12304 for 2.4

---

docs/discovering_hostedclusters.md

* Updated the MCE HC discovery doc to add backup labels
*  Backup and restore ACM configurations for auto-imported MCE HCs
* https://issues.redhat.com/browse/ACM-12222
```script
```

ACM-12222: MCE HC discovery backup and restore doc

---

docs/discovering_hostedclusters.md

Update discovery doc 0711

---

docs/creating_role_sts_aws.md
docs/provision_hosted_cluster_on_mce_local_cluster.md

AWS STS doc

---

docs/advanced/aks_configuration.md
pkg/install/hypershift.go
pkg/install/hypershift_test.go
pkg/manager/manifests/templates/clusterrole.yaml
pkg/manager/manifests/templates/deployment.yaml
pkg/util/constant.go

* RBAC changes
* Support external DNS configuration for Azure
*  For the addon agent to run in an AKS cluster and install the hypershift operator
* https://issues.redhat.com/browse/ACM-10781
```script
```

ACM-10781: AKS support

---

pkg/manager/cli_download_install.go

* This PR to make changes in the hypershift addon manager to determine whether to deploy the HCP CLI download based on the cloud vendor. The HCP CLI download is only deployed if the manager runs in OCP.
*  
* https://issues.redhat.com/browse/ACM-10781
```script
```

ACM-10781: Changes in the hypershift addon manager to support AKS

---

pkg/manager/cli_download_install.go
pkg/manager/manifests/templates/clusterrole.yaml

* Cherrypicks from main to 2.5
*  
* https://issues.redhat.com/browse/ACM-14414
```script
```

Cherrypicks 2.5 0923

---

pkg/manager/manifests/templates/clusterrole.yaml

* Adding coreos podmonitors permission
*  
* 
```script
```

Add podmonitors 2.4

---

pkg/manager/cli_download_install.go
pkg/manager/manifests/templates/clusterrole.yaml

* Cherry picks from main
*  
* https://issues.redhat.com/browse/ACM-14413
```script
```

Cherrypicks 0923

---

docs/supported_versions.md

* Document how to set the update channel in a hosted cluster
* Document supported OCP versions
* Document hosted cluster update recommendations
*  
* https://issues.redhat.com/browse/ACM-10876
```script
```

ACM-10876: cluster version update doc

---

docs/supported_versions.md

* Added a note about supported OCP version range for MCE managed clusters.
*  
* 
```script
```

add MCE supported versions

---

docs/advanced/aks_configuration.md

doc update

---

docs/advanced/running_mce_acm_addons_hostedmode.md
docs/discovering_hostedclusters.md
docs/provision_hosted_cluster_on_mce_local_cluster.md
pkg/agent/auto_import_controller.go

* Added missing ManagedCluster vendor and cloud auto-detect labels
*  Some custom or ACM logics might depend on auto-detected vendor and cloud.
* https://issues.redhat.com/browse/ACM-16840
```script
```

ACM-16840: added missing ManagedCluster auto-detect labels (#384)

---

pkg/agent/agent.go

* The agent copies the hosted cluster's kubeadmin password and kubeconfig secrets to the hub cluster. When OAuth is configured in the hosted cluster, the hypershift operator deletes the kubeadmin password secret from the hosted cluster but the mirrored kubeadmin password secret that the agent initially copied over to the hub remains in the hub. This change ensures that the secret gets deleted or re-created depending on the OAuth configuration in the hosted cluster.
*  
* https://issues.redhat.com/browse/ACM-17573
```script
```

ACM-17106: fix the management of mirrored admin secrets (#389)

---

.tekton/hypershift-addon-operator-mce-28-pull-request.yaml
.tekton/hypershift-addon-operator-mce-28-push.yaml

* Added konflux pipeline files to main
*  
* 
```script
```

added konflux pipeline files

---

go.mod
go.sum

A recent bug might impact hypershift users, refer to https://github.com/open-cluster-management-io/addon-framework/pull/298.
Create this PR to upgrade the addon-framework. 
Depends on PR https://github.com/open-cluster-management-io/addon-framework/pull/299. 
The bug in the addon-framework affects the manually created ManagedClusterAddon with AddonDeploymentConfigs, and it seems the hypershift mca is not created automatically so the users might be affected.
* 
```script
```

upgrade addon-framework

---

Dockerfile
Dockerfile.canary

* Update to use ubi9
*  
* 
```script
```

Update to use ubi9

---

pkg/manager/manager.go
pkg/manager/manifests/templates/deployment.yaml

* configurable resource limits and requests
*  Ensure all RHACM add-ons adopt the standard way for adjusting resource limits and requests.
* https://issues.redhat.com/browse/ACM-19016
```script
```

ACM-19016: configurable resource limits and requests

---

.tekton/hypershift-addon-operator-mce-29-pull-request.yaml
.tekton/hypershift-addon-operator-mce-29-push.yaml

* Updated the konflux tekton pipeline to build on main branch PRs.
*  
* 
```script
```

konflux PR event for main as well

---

.tekton/hypershift-addon-operator-mce-29-pull-request.yaml
.tekton/hypershift-addon-operator-mce-29-push.yaml

* Fixing https://github.com/stolostron/hypershift-addon-operator/pull/509/checks?check_run_id=41655729620
*  
* 
```script
```

Fix konflux PR 509

---

.tekton/hypershift-addon-operator-mce-29-push.yaml
Dockerfile.rhtap

* Adding multi archs and platforms for konflux push pipeline
*  To build multi-arch container images in konflux
* 
```script
```

Adding multi arch, platforms for konflux push pipeline

---

.tekton/hypershift-addon-operator-mce-29-pull-request.yaml
.tekton/hypershift-addon-operator-mce-29-push.yaml

* This PR incorporates https://github.com/stolostron/hypershift-addon-operator/pull/506
*  
* 
```script
```

Added Konflux service account

---

pkg/agent/agent.go

* Cherrypick https://github.com/stolostron/hypershift-addon-operator/pull/530
*  
* 
```script
```

Cherrypick PR530

---

renovate.json

Added renovate.json to block konflux dependency update PRs

---

.tekton/hypershift-addon-operator-mce-28-pull-request.yaml
.tekton/hypershift-addon-operator-mce-28-push.yaml

* Replaces https://github.com/stolostron/hypershift-addon-operator/pull/505
*  
* 
```script
```

Konflux sa (https://github.com/stolostron/hypershift-addon-operator/pull/505)

---

docs/discovering_hostedclusters.md

Discovery doc update

---

docs/discovering_hostedclusters.md

* Updated the hosted cluster discovery doc to add extra information about using an empty string as the discovery prefix.
*  
* https://issues.redhat.com/browse/ACM-23573
```script
```

ACM-23573: update the discovery doc

---

docs/discovering_hostedclusters.md
scripts/README.md
scripts/backup-mce-resources.sh
scripts/cleanup-mce-acm-integration.sh
scripts/enable-hypershift-addon.sh
scripts/import-mce-cluster.sh
scripts/setup-acm-hub.sh
scripts/setup-autoimport-policy.sh
scripts/setup-mce-acm-integration.sh
scripts/undo-acm-hub.sh
scripts/undo-hypershift-addon.sh
scripts/undo-import-mce-cluster.sh
scripts/verify-mce-integration.sh

* Added scripts to configure HCP discovery
*  
* 
```script
```

Added scripts to configure HCP discovery
