stolostron/hypershift-addon-operator

Makefile
example/addon-manager-deployment.yaml
pkg/agent/agent.go
pkg/manager/manager.go
pkg/manager/manifests/templates/deployment.yaml
pkg/util/constant.go

- make the hypershift operator image configurable, by setting an Env `HYPERSHIFT_OPERATOR_IMAGE_NAME` for the addon mgr
- change the default image from `quay.io/ianzhang366/hypershift-addon-operator:latest` to `quay.io/stolostron/hypershift-addon-operator:latest`
After this merged, I will add these two Envs `HYPERSHIFT_ADDON_IMAGE_NAME` and `HYPERSHIFT_OPERATOR_IMAGE_NAME` into https://github.com/stolostron/hypershift-addon-chart.

Make the hypershift operator image configurable

---

pkg/manager/manager.go

Disable the install strategy all, all means the manager will install the addon on ALL managed clusters automatically, but we want to install it by users manually.

Disable install strategy all

---

README.md
example/addon-manager-deployment.yaml
pkg/agent/agent.go
pkg/manager/manager.go
pkg/manager/manifests/templates/deployment.yaml
pkg/util/constant.go

The bucket secret namespace **must** be the clusterName namespace, otherwise, the agent getting the secret will fail(permission problem, the permission manifest just grant the agent getting secret in the clusterName namespace)

Delete bucket namespace flag

---

pkg/agent/agent.go
pkg/agent/hypershift.go
pkg/manager/manifests/templates/clusterrole.yaml
pkg/util/constant.go

- mark deployment directly instead of use the managedclusteraddon
- mount the multicluster pull secret to hypershift's serviceaccount for downstream images

use deployment annotation to mark the creation

---

pkg/agent/hypershift.go
pkg/manager/manifests/templates/deployment.yaml

When a new image is available. We also did not upgrade any of the other resources.
* Now patch all resources with changes
* Changed the imagePullPolicy from Always to IfNotPresent
* Make sure that when a new hypershift-operator is available we patch all kube resources related to the `hypershift-operator`
*  The hypershift-operator will not be upgraded otherwise.
* https://issues.redhat.com/browse/ACM-1321
```script
ok      github.com/stolostron/hypershift-addon-operator/pkg/agent       0.018s  coverage: 6.0% of statements
?       github.com/stolostron/hypershift-addon-operator/pkg/manager     [no test files]
? …
```

Noticed that we did no upgrade the hypershift-operator 

---

pkg/agent/agent.go
pkg/manager/manager.go
pkg/manager/manifests/templates/deployment.yaml
pkg/util/constant.go

* Add image pull secret for addon agent
*  The addon agent can not be installed in QE environment
* https://github.com/stolostron/backlog/issues/22321
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	0.031s	coverage: 6.0% of statements
```

Add image pull secret for addon agent

---

Dockerfile
Makefile
go.mod

* Bump golang to 1.18
*  The upstream hypershift project is using golang 1.18, and hypershift-addon-operator builds the hypershift cli binary in there image.
* https://github.com/stolostron/backlog/issues/22238
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	0.036s	coverage: 6.0% of statements
```

Bump golang to 1.18

---

pkg/agent/hypershift.go
pkg/agent/hypershift_test.go

* Check to see if the addon annotation is present to decide whether we should upgrade or not.
* Added functional tests for this function and a similar function.
*  This makes sure we don't accidentally upgrade a hypershift-operator that the addon did not deploy.
* https://issues.redhat.com/browse/ACM-1321
```script
ok      github.com/stolostron/hypershift-addon-operator/pkg/agent       0.020s  coverage: 10.3% of statements
?       github.com/stolostron/hypershift-addon-operator/pkg/manager     [no test files]
?       github.com/stolostron/hypershift-addon-operator/pkg/util        [no test files]
```

Annotation check

---

README.md
pkg/agent/hypershift.go
pkg/agent/hypershift_test.go

* A user currently requires to create S3 bucket secret on the hub for the hypershift addon to install hypershift operator on a hosting cluster. S3 bucket secret is required only if you plan to create hosted clusters on AWS platform.
* TODO in backplane 2.1: Make the addon configurable with other hypershift operator installation options.
*  We want to enable the hypershift addon without the S3 bucket secret for non-AWS platform provisioning,
* https://github.com/stolostron/backlog/issues/22814
```script
r github.com/stolostron/hypershift-addon-operator/pkg/util -coverprofile cover.out
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	11.465s	coverage: 69.6% of …
```

s3 bucket secret should be optional

---

pkg/agent/agent.go
pkg/agent/agent_test.go
pkg/util/constant.go

* Per SD request, update kubeconfig and kubeadmin-password secrets in managed cluster NS to use infraID in the name:
```
[infraID]-admin-kubeconfig 
[infraID]-kubeadmin-password 
```
Also needed new labels to help with filtering:
```
labels:
cluster-name: [hd-name]
hosting-namespace:[hosting NS]
```
*  Old name contains the hosting NS and HD name which users don't know
* https://issues.redhat.com/browse/CMCS-102
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	7.290s	coverage: 69.9% of statements
?   	github.com/stolostron/hypershift-addon-operator/pkg/util	[no test …
```

Change name of kubeconfig and kubeadmin-password to use infraId

---

go.mod
go.sum

* Update the go mod hypershift version
*  to match hypershift deployment controller's hypershift version
* https://issues.redhat.com/browse/ACM-1447
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	5.503s	coverage: 70.0% of statements
```
/assign @jnpacker 
/assign @philipwu08 
/assign @rokej 
/assign @zhujian7

Update hypershift version to match hypershift deployment controller

---

pkg/agent/agent.go
pkg/agent/agent_test.go

*  Create `external-managed-kubeconfig` with internal hosted cluster kube API server URL so in both private and public modes, the registration agent can connect to the hosted cluster's API server for managed cluster registration.
* https://github.com/stolostron/backlog/issues/23514#issuecomment-1157738028
*  To support private mode hosted clusters
* https://github.com/stolostron/backlog/issues/23514
* https://issues.redhat.com/browse/ACM-1466
```script
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestReconcile$ github.com/stolostron/hypershift-addon-operator/pkg/agent
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	0.843s
```
Deployed an AWS hosted cluster successfully and the server URL in …

support private link hosted cluster

---

Dockerfile
pkg/manager/manifests/templates/deployment.yaml

* Remove user id from Dockerfile
* Add reduced security context in the deployment
*  During runtime analysis pod(s) were identified not using the OpenShift restricted SCC.
* https://github.com/stolostron/backlog/issues/23950
Verified that the addon agent container runs fine and reconciles. 
```script
rokej@rjung-mac HypershiftAgent % kubectl logs hypershift-addon-agent-7687684966-dz8rq -n open-cluster-management-agent-addon
I0712 01:22:50.301235       1 request.go:601] Waited for 1.047915861s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/autoscaling.openshift.io/v1beta1?timeout=32s
2022-07-12T01:22:58.614Z	INFO	agent.agent-reconciler	agent/hypershift.go:200	enter runHypershiftInstall …
```

Reduce pod privilege

---

pkg/manager/manifests/templates/deployment.yaml

* In the hypershift addon agent deployment YAML, disable readOnlyRootFilesystem in the container security context because the agent needs to write a hypershift image override reference file to the /tmp filesystem for hypershift operator installation.
*  Same as above
* https://github.com/stolostron/backlog/issues/24122
Now the addon agent can write to /tmp/hypershift-imagestream742529715 and install the hypershift operator with `--image-refs /tmp/hypershift-imagestream742529715` parameter.
```script
kubectl logs hypershift-addon-agent-6fc8794694-rlqdq -n open-cluster-management-agent-addon
I0714 17:29:33.037209       1 request.go:601] Waited for 1.046798497s due to client-side throttling, not priority and fairness, request: …
```

disable readOnlyRootFilesystem

---

pkg/agent/agent.go
pkg/agent/hypershift.go
pkg/agent/hypershift_test.go

* Add missing External DNS support
*  This is one of three missing `hypershift install --help` options
* https://issues.redhat.com/browse/ACM-1558
```script
ok      github.com/stolostron/hypershift-addon-operator/pkg/agent       5.559s  coverage: 72.3% of statements
?       github.com/stolostron/hypershift-addon-operator/pkg/manager     [no test files]
?       github.com/stolostron/hypershift-addon-operator/pkg/util        [no test files]
```

Add missing support for External DNS parameters and credentials

---

pkg/agent/hypershift.go

* Enable telemetry when the addon installs hypershift operator so that it can forward control plane telemetry correctly.
*  
* https://issues.redhat.com/browse/ACM-1574
The hypershift operator container runs with the telemetry arguments.
```script
containers:
- args:
- run
- --namespace=$(MY_NAMESPACE)
- --pod-name=$(MY_NAME)
- --metrics-addr=:9000
- --enable-ocp-cluster-monitoring=false
- --enable-ci-debug-output=false
- --private-platform=None
- --oidc-storage-provider-s3-bucket-name=rj-aws-hyper
- --oidc-storage-provider-s3-region=us-east-1
- --oidc-storage-provider-s3-credentials=/etc/oidc-storage-provider-s3-creds/credentials
- --enable-uwm-telemetry-remote-write
command:
- /usr/bin/hypershift-operator
env:
- name: MY_NAMESPACE
valueFrom: …
```

enable telemetry in hypershift operator installation

---

go.mod
pkg/agent/agent.go
pkg/agent/agent_test.go
pkg/install/hypershift.go
pkg/install/hypershift_executor.go
pkg/install/hypershift_test.go
pkg/install/upgrade.go
pkg/install/upgrade_test.go
pkg/util/constant.go

* This features enables the ability to upgrade images for individual HyperShift operators through a configmap. When an image(s) is updated in the configmap (open-cluster-management-agent-addon/hypershift-upgrade-images), the HyperShift add-on pod is restarted and the HyperShift operator is upgraded with the images in the configmap.
*  This allows Service Delivery to define an upgrade strategy for their Management Clusters (specifically the Hypershift Addon). 
* https://issues.redhat.com/browse/ACM-1648
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	12.148s	coverage: 61.4% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	2.920s	coverage: 80.8% of statements
```

Support upgrade of images for Hypershift operators

---

pkg/agent/agent.go
pkg/agent/agent_test.go

* Create secrets on the hub when the progress of the HC is completed
*  The OCP version of the managed cluster could be wrong if the secrets are created too early.
* https://github.com/stolostron/backlog/issues/24918
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	12.823s	coverage: 72.1% of statements
```

Create secrets on the hub when the progress of the HC is completed

---

docs/upgrading_hypershift_operator.md

* The image override configmap name was changed and the doc needs to be updated to use the new name.
*  The old name is incorrect.
* https://issues.redhat.com/browse/ACM-1648
```script
```

Update image override configmap name in the doc

---

docs/provision_hosted_cluster_on_mce_local_cluster.md

Signed-off-by: David Huynh <dhuynh@redhat.com>
* HypershiftDeployment custom resource and its controller are removed in MCE 2.2. This requires users to use individual resources like `HostedCluster`, `NodePool`, and `ManagedCluster` to provision a hosted cluster and import it as a MCE managed cluster. This user story is to document steps to do these using CLI.
* Steps in this doc was verified using ACM 2.6.1, but is applicable to ACM 2.7 once the hypershift operator is updated on MCE 2.2.
*  Users can easily follow the document to provision a hosted cluster on MCE hub (local-cluster).
*  The hosted cluster is auto-imported as a managed cluster.
*  UI displays the hosted cluster / managed cluster correctly.
* https://issues.redhat.com/browse/ACM-1658
```script
```

Document how to create a hosted cluster on local-cluster without HypershiftDeployment

---

go.mod
pkg/agent/agent.go
pkg/agent/agent_test.go
pkg/install/hypershift.go
pkg/install/hypershift_executor.go
pkg/install/hypershift_test.go
pkg/install/upgrade.go
pkg/install/upgrade_test.go
pkg/util/constant.go

* This features enables the ability to upgrade images for individual HyperShift operators through a configmap. When an image(s) is updated in the configmap (open-cluster-management-agent-addon/hypershift-upgrade-images), the HyperShift add-on pod is restarted and the HyperShift operator is upgraded with the images in the configmap.
*  This is for back-porting the work that was done for MCE 2.2 in https://github.com/stolostron/hypershift-addon-operator/pull/73
* https://issues.redhat.com/browse/ACM-1759
```script
ok      github.com/stolostron/hypershift-addon-operator/pkg/agent       10.534s coverage: 61.6% of statements
ok      github.com/stolostron/hypershift-addon-operator/pkg/install     1.680s  coverage: 80.8% of statements
```

Back-port upgrade of images for Hypershift operators

---

pkg/agent/agent.go
pkg/install/hypershift.go
pkg/install/hypershift_test.go
pkg/install/install_job.go
pkg/install/upgrade.go
pkg/install/upgrade_test.go
pkg/manager/manifests/templates/clusterrole.yaml
pkg/util/constant.go

* A job is used to install the HyperShift operator. This container created from the job uses the HyperShift operator image specified in the imagestream, or the hypershift-override-images configmap if it exists. By using the HyperShift CLI from the target HyperShift operator image to install the HyperShift operator, all resources, including the CRDs, are upgraded to the level of the target HyperShift operator image.
*  The previous implementation uses the templates output from HyperShift render function to upgrade the HyperShift operator. The resource templates, including CRDs, are specific to the version of HyperShift bundled with the HyperShift agent addon.  As a result, there may be a mismatch between the HyperShift resources from the render …

Use job to install HyperShift operator

---

pkg/agent/agent.go
pkg/install/hypershift.go
pkg/install/hypershift_test.go
pkg/install/install_job.go
pkg/install/upgrade.go
pkg/install/upgrade_test.go
pkg/manager/manifests/templates/clusterrole.yaml
pkg/util/constant.go

* A job is used to install the HyperShift operator. This container created from the job uses the HyperShift operator image specified in the imagestream, or the hypershift-override-images configmap if it exists. By using the HyperShift CLI from the target HyperShift operator image to install the HyperShift operator, all resources, including the CRDs, are upgraded to the level of the target HyperShift operator image.
*  The previous implementation uses the templates output from HyperShift render function to upgrade the HyperShift operator. The resource templates, including CRDs, are specific to the version of HyperShift bundled with the HyperShift agent addon. As a result, there may be a mismatch between the HyperShift resources from the render …

Use job to install HyperShift operator - 2.1

---

pkg/install/hypershift.go
pkg/install/hypershift_test.go

* Add support for a new key in the external DNS secret, `txt-owner-id`. If set, its value is plumbed into the `--external-dns-txt-owner-id` argument to the install job.
* Allows service delivery to support external DNS when installing hypershift via the addon.
* #86
closes: #86
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	5.784s	coverage: 61.6% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	91.645s	coverage: 84.0% of statements
```

Plumb in `--external-dns-txt-owner-id`

---

Dockerfile
go.mod

* Update golang version to 1.19
* Locally built the image and it deployed on an ACM environment fine (the pod ran successfully).
* Corresponding release repo PR https://github.com/openshift/release/pull/33147
*  golang version update is needed for security compliance.
* https://issues.redhat.com/browse/ACM-1826
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	0.677s	coverage: 61.6% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	91.807s	coverage: 84.0% of statements …
```

Update golang to 1.19

---

Dockerfile
go.mod

* We need to revert golang back to 1.18 because a CICD bug in DS build that is not related to us.
* **note** https://github.com/openshift/release/pull/33225 should be merged along this PR.
*  Ensure successful downstream build.
* https://github.com/stolostron/backlog/issues/26413
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	1.162s	coverage: 61.6% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	91.695s	coverage: 84.0% of statements
```

Revert golang back to 1.18

---

docs/upgrading_hypershift_operator.md
pkg/agent/agent.go
pkg/install/hypershift.go
pkg/install/hypershift_test.go
pkg/install/upgrade.go
pkg/install/upgrade_test.go
pkg/manager/manifests/permission/role.yaml
pkg/util/constant.go

* Detect changes in the hypershift operator installation options such as S3 bucket secret, external DNS secret, private link secret and image override configmap and re-install the hypershift operator on the hosting cluster if change is detected.
* To check for changes, connect to the hub to compare secrets and configmap in the hosting cluster namespace
* Check every 2 minutes
*  When users need to rotate/update the secrets or have a new set of hypershift operator images, there is currently no easy way to trigger the hypershift operator re-installation from the hub.
* https://issues.redhat.com/browse/ACM-1824
```script
```

ACM-1824 detect changes and re-install hypershift operator

---

docs/provision_hosted_cluster_on_mce_local_cluster.md
pkg/agent/agent.go
pkg/agent/agent_test.go
pkg/install/hypershift_test.go

* When importing HostedClusters.
* Currently you need the cluster.open-cluster-management.io/hypershiftdeployment, annotation (deprecated)
* Then if you want to use a different cluster name you need the cluster.open-cluster-management.io/managedcluster-name
* Modified the Addon controller to always produce an import secret regardless of the annotations.
*  hypershiftdeployment has been deprecated and removed, so it shouldn't be referenced in the flow
* https://issues.redhat.com/browse/ACM-1922
```script
ok      github.com/stolostron/hypershift-addon-operator/pkg/agent       9.101s  coverage: 61.4% of statements
ok …
```

Add support for the ManagedCluster-name annotation,

---

hack/crds/managedclusteraddons.crd.yaml
pkg/agent/addon_status_controller.go
pkg/agent/addon_status_controller_test.go
pkg/agent/addon_status_helper.go
pkg/agent/addon_status_helper_test.go
pkg/agent/agent.go
pkg/agent/suite_test.go
pkg/manager/manifests/permission/role.yaml
pkg/util/constant.go
test/e2e/install_test.go

* Watch Hypershift operator and external dns deployments
* Update hub hypershift managedclusteraddon status degraded condition accordingly
* Allows hub cluster admin to have better visibility to managed cluster's hypershift operator deployment status
* https://issues.redhat.com/browse/ACM-1684
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	19.382s	coverage: 70.2% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	126.431s	coverage: 86.0% of statements
```
Build, …

Add new addon status controller to check and set status based on Hypershift deployments statuses

---

docs/provision_hypershift_clusters_by_manifestwork.md

* A missing field in the manifestwork example which caused a continuous race condition reconciles between the manifestwork controller and the hypershift operator.
*  
* 
```script
```

Fix manifestwork doc

---

pkg/install/hypershift.go
pkg/install/hypershift_test.go

* fix incorrect usage of controllerutil.CreateOrUpdate()
* This was preventing changes to hypershift secret in the hub to be propagated to spoke clusters
* https://issues.redhat.com/browse/ACM-2056
* to fix https://issues.redhat.com/browse/ACM-2056
* https://issues.redhat.com/browse/ACM-2056
```script
```

fix incorrect usage of controllerutil.CreateOrUpdate()

---

docs/provision_hypershift_clusters_by_manifestwork.md

* Update the manifestwork HostedCluster deployment doc to add an additional annotation to enable only work and policy addons in hosted mode.
*  
* 
```script
```

Update the manifestwork HC doc

---

pkg/install/install_job.go

* The hypershift install job on managed clusters may fail with ImagePullError if the image pull secret is in the MCE, and not in the openshift default pull-secret. This change uses the image pull secret of the addon when creating the install job.
*  The hypershift install job on managed clusters may fail.
* https://issues.redhat.com/browse/ACM-1912
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	21.648s	coverage: 70.2% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	137.472s	coverage: 85.9% of statements
```

Use the addon image pull secret for the install job

---

docs/provision_hosted_cluster_on_mce_local_cluster.md
docs/provision_hypershift_clusters_by_manifestwork.md
docs/scheduling_hosted_cluster.md
pkg/agent/agent.go
pkg/agent/agent_test.go
pkg/agent/clusterclaim.go
pkg/agent/clusterclaim_test.go
pkg/manager/manager.go
pkg/util/constant.go

* Cluster claim `hostedclustercount.above.threshold.hypershift.openshift.io` was added to indicate that the number of HCs on a hosting cluster exceeding the threshold number
*  Cluster claim `hostedclustercount.zero.hypershift.openshift.io` was added to indicate that there is no hosted cluster on a hosting cluster
* The max and threshold numbers are configurable
* Documented these
* This PR goes with https://github.com/stolostron/backplane-operator/pull/356
*  Better scheduling of a hosted cluster
* https://issues.redhat.com/browse/ACM-2266
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	20.603s	coverage: 72.5% of statements
ok …
```

add cluster claims to indicate HC count above threshold or at zero

---

Dockerfile
go.mod

* We need to revert golang back to 1.18 because a CICD bug in DS build that is not related to us.
*  Ensure successful downstream build.
* https://github.com/stolostron/backlog/issues/26413
```script
not applicable
```

Revert back to golang 1.18

---

pkg/agent/agent.go
pkg/agent/agent_test.go

* The external managed kubeconfig secret's server URL is currently hardcoded to use port 6443. Instead, it should use the same port in the admin-kubconfig secret's server URL.
*  This change will support the scenario for the apiserver to use the non-default port of 6443.
* https://issues.redhat.com/browse/ACM-2311
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	19.557s	coverage: 72.7% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	137.138s	coverage: 86.6% of statements
```

External managed kubeconfig secret support for custom api server port

---

docs/installing_hypershift_cli.md
pkg/manager/cli_download_install.go
pkg/manager/manifests/cli/consoledownload.yaml

* Renaming the CLI name from `oc hcp` to `hypershift` to be consistent with upstream documentation and command line help.
*  Consistency
* 
```script
```

Rename CLI to hypershift

---

pkg/manager/manifests/cli/deployment.yaml

* Set the preferred node affinity for the hypershift-cli-deployment so that the pod is deployed on the infra nodes
*  The hypershift-cli-deployment could be deployed on any worker node without the preferred node affinity. The deployment spec has a toleration for the infra node role, however, this requires the node to have a corresponding taint.
* https://issues.redhat.com/browse/ACM-2402
```script
```

Set node affinity for HS cli deployment to infra node role

---

docs/enable_hypershift_operator_RHOBS.md
pkg/install/hypershift.go
pkg/install/hypershift_test.go
pkg/install/install_job.go
pkg/manager/manifests/templates/deployment.yaml

* The addon agent used wrong environment variable ENABLE_RHOBS_MONITORING which caused the hypershift operator installation to fail in SD environment.
*  
* https://issues.redhat.com/browse/ACM-2492
```script
```

fix enabling RHOBS on hypershift operator

---

pkg/agent/agent.go
pkg/agent/agent_test.go
pkg/install/hypershift.go

* When the agent reconcile fails to create external-managed-kubeconfig secret in the hosted cluster's klusterlet namespace or hub mirror secret, requeue the reconcile until it succeeds.
* This fixes the current assumption that the klusterlet is available when the hosted control plane becomes available.
* This fixes the current assumption that a managed cluster is created before a hosted cluster. 
* https://issues.redhat.com/browse/ACM-2208
```script
KUBEBUILDER_ASSETS="/Users/rokej/Library/Application Support/io.kubebuilder.envtest/k8s/1.22.1-darwin-amd64" go test github.com/stolostron/hypershift-addon-operator/cmd github.com/stolostron/hypershift-addon-operator/pkg/agent github.com/stolostron/hypershift-addon-operator/pkg/install …
```

requeue reconcile for klusterlet secrets

---

pkg/install/hypershift.go
pkg/install/hypershift_test.go

* Set this when RHOBS monitoring is enabled to expose more metrics in SD environment.
*  
* https://issues.redhat.com/browse/ACM-2676
```script
```

set hypershift metrics set differently for RHOBS

---

pkg/install/install_job.go

* The installation job and pods were automatically cleaned-up after 5 mins. This time is extended to 48 hrs with the latest change.
*  Users may need more time to investigate the failure, but the installation logs may be cleaned-up already. Extending the time to 48 hrs will give users more time to investigate.
* https://issues.redhat.com/browse/ACM-2680
```script
```

Change cleanup of Hypershift operator install job to 48 hrs

---

pkg/agent/agent.go
pkg/agent/agent_test.go
pkg/manager/manager.go
pkg/manager/manifests/templates/metrics-servicemonitor.yaml
pkg/manager/manifests/templates/work-agent-clusterrole-rhobs.yaml
pkg/manager/manifests/templates/work-agent-clusterrolebinding-rhobs.yaml

* Add option to enable RHOBS monitoring
* Fix API server port number in external-managed-kubeconfig
*  
* API server port issue https://issues.redhat.com/browse/ACM-2632
```script
```

enable RHOBS monitoring and fix api server port

---

docs/provision_hosted_cluster_on_mce_local_cluster.md

* Add doc to create KlusterletAddonConfig to enable all ACM addons in a hypershift hosted cluster
*  
* https://issues.redhat.com/browse/ACM-2361
```script
oc get managedclusteraddon -n rj-0117a
NAME                          AVAILABLE   DEGRADED   PROGRESSING
application-manager           True                   
cert-policy-controller        True                   
cluster-proxy                 True                   
config-policy-controller      True                   
governance-policy-framework   True                   
iam-policy-controller         True                   
work-manager                  True    
```

add doc to create KlusterletAddonConfig

---

test/canary/run_canary_test.sh

* Added trap to ensure that AWS resources get cleaned up whenever the script is terminated.
*  
* 
```script
```

fix canary test script

---

Dockerfile.canary
test/canary/run_canary_test.sh

* The `ubuntu` image doesn't exist in PROW. Update the canary test to build and run using `ubi` image.
*  Ensure canary test PROW build successfully.
* https://issues.redhat.com/browse/ACM-2811
```script
Ran the docker build and executed the test locally against ck cluster. It seems to be fine.
```

Use ubi-minimal as the docker base image for canary test execution

---

pkg/agent/agent.go
pkg/install/install_job.go
pkg/install/upgrade.go
pkg/install/upgrade_test.go

* Changed installation job to keep trying if the prev job failed. Install job does not need to create a pod (1 pod for each job) to retry the installation anymore. Removed invoking install job from agent startup, but instead use the same upgrade logic. May want to keep jobs around for less than 48 hrs now that the failed jobs keep retrying.
*  Install job used to fail too quickly. If dependencies eventually resolve, but the install job does not retry.
* https://issues.redhat.com/browse/ACM-3190
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	18.987s	coverage: 72.2% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	158.009s	coverage: 85.9% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/manager	1.268s	coverage: …
```

Make install job keep retrying if it fails

---

Dockerfile.canary
test/canary/README.md
test/canary/hypershift-failed.xml
test/canary/hypershift-success.xml
test/canary/run_canary_test.sh

* CICD requires all the canary test to produce a success or failed junit xml result file depending on the result of the canary test.
* The Success and Failure result data is mocked because we are not using a test framework like Gingko.
* The real useful outputs (such as outputs from echo commands) will be captured by the CICD "run_test.sh"
*  CICD requirement for canary test to produce a XML file that follows a certain format
* ACM-2811
```script
built canary docker image and ran it locally and it seems to be fine.
```

Produce junit xml result file based for canary test

---

Dockerfile.canary

* fix canary test image not having tar
*  successful canary test run
* ACM-2811
```script
not appilcable
```

fix canary test image not having tar

---

test/canary/resources/hosted_cluster_manifestwork.yaml

* remove optional storage class name specification
*  so that canary test can be run on GCP cluster
* ACM 2811
```script
not applicable
```

remove optional storage class name specification

---

test/canary/run_canary_test.sh

* Skip execution of canary test (report success) on non AWS cluster
*  Canary is running on different platforms but so far we can only support AWS
* ACM-2811 ACM-3290
```script
tested the inverse logic against AWS cluster and saw the test skipped successfully.
```

Skip execution of canary test (report success) on non AWS cluster

---

test/canary/README.md
test/canary/run_canary_test.sh

* We discover that the recent DS hypershift binary only supports Openshift version 4.11 and above.
*  Ensure canary successful execution.
* ACM-2811
```script
Supported Openshift version 4.11.0
```

Skip canary test execution if the Openshift version is 4.10 and under

---

Makefile

* fix clusteradm to a specific version
*  fix e2e
* na
```script
make ensure-clusteradm 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  4799  100  4799    0     0   101k      0 --:--:-- --:--:-- --:--:--  104k
Your system is linux_amd64
Installing clusteradm CLI...
Installing v0.4.0 OCM clusteradm CLI...
Downloading https://github.com/open-cluster-management-io/clusteradm/releases/download/v0.4.0/clusteradm_linux_amd64.tar.gz ...
clusteradm installed into /home/mng/go/bin successfully.
To get started with clusteradm, please visit https://open-cluster-management.io/getting-started/
CLUSTERADM=/home/mng/go/bin/clusteradm
```

Fix clusteradm to v0.4.0 to fix e2e

---

pkg/install/hypershift.go
pkg/install/hypershift_test.go

* Do not add `--enable-uwm-telemetry-remote-write` HO install argument in SD (when RHOBS is enabled)
*  SD environment configuration
* https://issues.redhat.com/browse/ACM-3648
```script
ok      github.com/stolostron/hypershift-addon-operator/pkg/agent       19.398s coverage: 71.7% of statements
ok      github.com/stolostron/hypershift-addon-operator/pkg/install     277.210s        coverage: 87.1% of statements
ok      github.com/stolostron/hypershift-addon-operator/pkg/manager     0.634s  coverage: 56.2% of statements
ok      github.com/stolostron/hypershift-addon-operator/pkg/metrics     0.527s  coverage: 100.0% of statements
?       github.com/stolostron/hypershift-addon-operator/pkg/util        [no test …
```

remove enable-uwm-telemetry-remote-write for sd

---

pkg/agent/agent_test.go
pkg/install/hypershift.go
pkg/install/hypershift_test.go
pkg/util/constant.go

* Do not add `hypershift.open-cluster-management.io/createBy: hypershift-addon` annotation to HO deployment
* Do not check for the existence of the annotation to determine whether to update, always update
* Do not update-install if `hypershift.open-cluster-management.io/not-by-mce: true` annotation is added to HO deployment by users manually
*  to ensure that HO gets updated to be compatible with ACM/MCE
* https://issues.redhat.com/browse/ACM-3477
```script
```

always update-install existing HO when special annotation is absent

---

.gitignore
Makefile
hack/install_ocm.sh

* Undo the fixed version clusteradm workaround. Build the latest clusteradm at e2e runtime.
*  Undo workaround fix in e2e
* NA
```script
NA
```

Fix e2e by removing temporary fixed version of clusteradm and installing latest clusteradm at runtime

---

pkg/agent/agent.go
pkg/agent/agent_test.go
pkg/manager/manifests/templates/clusterrole.yaml

* Delete the managed cluster when the hosted cluster is deleted
*  There are issues if the managed cluster is reused for another hosted cluster with the same name. By deleting the managed cluster when the HC is deleted, this performs the necessary cleanup and not have an orpaned MC. If another HC with the same name is provisioned, then user would need to create a new MC again.
* https://issues.redhat.com/browse/ACM-2094
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	20.979s	coverage: 72.1% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	277.322s	coverage: 87.1% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/manager	1.384s	coverage: 56.2% of statements
ok …
```

Delete managed cluster when hosted cluster is deleted

---

pkg/manager/manager.go

* Don't attempt to enable the hypershift cli download on OCP clusters with no console
*  > may result in a spurious false-positive error in the log that could cause unnecessary concern when doing PD, and if logic were ever added following the CR-creation code then there might be short-circuiting of other important stuff
* https://issues.redhat.com/browse/ACM-3863
```script
ok      github.com/stolostron/hypershift-addon-operator/pkg/agent       22.399s coverage: 72.2% of statements
ok      github.com/stolostron/hypershift-addon-operator/pkg/install     280.763s        coverage: 87.0% of statements
ok      github.com/stolostron/hypershift-addon-operator/pkg/manager     0.047s  coverage: 55.6% of statements
ok …
```

ACM-3863 dont enable hypershift cli download on consoleless OCP

---

docs/hypershift_operator_installation.md
pkg/agent/agent_test.go
pkg/install/hypershift.go
pkg/install/hypershift_test.go
pkg/install/upgrade.go
pkg/install/upgrade_test.go
pkg/manager/cli_download_install.go
pkg/manager/cli_download_install_test.go
pkg/util/constant.go

* Allow users to add or remove hypershift operator installation options
* Tests and documentation
*  So users can customize the hypershift operator installations
* https://issues.redhat.com/browse/ACM-4093
```script
KUBEBUILDER_ASSETS="/Users/rokej/Library/Application Support/io.kubebuilder.envtest/k8s/1.22.1-darwin-amd64" go test github.com/stolostron/hypershift-addon-operator/cmd github.com/stolostron/hypershift-addon-operator/pkg/agent github.com/stolostron/hypershift-addon-operator/pkg/install github.com/stolostron/hypershift-addon-operator/pkg/manager github.com/stolostron/hypershift-addon-operator/pkg/metrics github.com/stolostron/hypershift-addon-operator/pkg/util -coverprofile cover.out
ok …
```

Ho install flags overrides

---

pkg/manager/cli_download_install.go
pkg/manager/cli_download_install_test.go
pkg/manager/manager.go

* Fix hypershift CLI download code that is broken by a couple of recent commits
* Fix the code that fails to list MulticlusterEngines resources (https://github.com/stolostron/backplane-operator/pull/400)
* Fix the code that tries to figure out if there is ConsoleCLIDownload resource (or CRD)
*  Currently the manager does not deploy the hypershift CLI download
* https://issues.redhat.com/browse/ACM-4230
* https://github.com/stolostron/backlog/issues/27211
```script
Running tool: /usr/local/bin/go test -timeout 180s -coverprofile=/var/folders/6m/zwb5lxd157bgxp_wm4bv95fc0000gn/T/vscode-go3tqeO2/go-code-cover -run ^TestEnableHypershiftCLIDownload$ github.com/stolostron/hypershift-addon-operator/pkg/manager
ok  	github.com/stolostron/hypershift-addon-operator/pkg/manager	0.951s	coverage: 48.2% …
```

fix CLI download deployment

---

pkg/agent/agent.go
pkg/agent/clusterclaim.go
pkg/agent/clusterclaim_test.go
pkg/manager/manifests/permission/role.yaml

* Fix the code that creates/updates the admin-kubeconfig in the hub. Currenly, it only creates a new one but does not update the existing cert when the HC API server cert is renewed.
* Fix the code that generates a cluster claim in the hosted cluster. This code needs to be aware of the custom API server cert. 
*  Support HC API server with a custom certificate
* https://issues.redhat.com/browse/ACM-3990
```script
KUBEBUILDER_ASSETS="/Users/rokej/Library/Application Support/io.kubebuilder.envtest/k8s/1.22.1-darwin-amd64" go test github.com/stolostron/hypershift-addon-operator/cmd github.com/stolostron/hypershift-addon-operator/pkg/agent github.com/stolostron/hypershift-addon-operator/pkg/install github.com/stolostron/hypershift-addon-operator/pkg/manager …
```

additional code change to support custom API server cert

---

example/addon-manager-deployment.yaml
pkg/agent/agent.go
pkg/agent/agent_test.go
pkg/manager/manager.go
pkg/manager/manifests/permission/clusterrole.yaml
pkg/manager/manifests/permission/clusterrolebinding.yaml
test/e2e/install_test.go

* When HC is deleted, managed cluster is not getting deleted from the hub and SA doesn't have required permissions. Also, changed order to delete the managed cluster before updating klusterlet to remove finalizer.
*  Fixes the deletion of the managed cluster when the HC is deleted.
* https://issues.redhat.com/browse/ACM-2094
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	14.390s	coverage: 70.7% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	176.229s	coverage: 86.0% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/manager	1.232s	coverage: 55.8% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/metrics	0.517s	coverage: 100.0% of statements
```

Managed cluster not getting deleted when HC is deleted

---

example/addon-manager-deployment.yaml
pkg/agent/agent.go
pkg/agent/agent_test.go
pkg/metrics/addon-agent-health-metrics.go
test/e2e/install_test.go

* Fix the code that assumes all HCs have kubeadmin-password secret
* Generate metrics data to calculate reconcile error rate
* Fix e2e test
*  To generate the overall SLO of the agent that takes part in HC creations
* https://issues.redhat.com/browse/ACM-4446
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	23.639s	coverage: 72.3% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	176.305s	coverage: 86.0% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/manager	0.591s	coverage: 58.3% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/metrics	0.938s	coverage: 100.0% of statements
? …
```

reconcile error rate metrics

---

pkg/agent/agent.go
pkg/agent/agent_test.go
pkg/metrics/addon-agent-health-metrics.go

* Fix the code that assumes all HCs have kubeadmin-password secret
* Generate metrics data to calculate reconcile error rate
*  To generate the overall SLO of the agent that takes part in HC creations
* https://issues.redhat.com/browse/ACM-4447
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	34.390s	coverage: 74.1% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	281.406s	coverage: 87.0% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/manager	1.233s	coverage: 56.2% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/metrics	0.519s	coverage: 100.0% of statements
?   	github.com/stolostron/hypershift-addon-operator/pkg/util …
```

SLO metrics

---

pkg/manager/cli_download_install.go
pkg/manager/cli_download_install_test.go

* Add retry on getting csv in case permissions are not yet granted
*  During upgrade, clusterrole may be updated after pod which results in pod requestiong resources it doesn't have permission for
* https://issues.redhat.com/browse/ACM-3429
```script
ok      github.com/stolostron/hypershift-addon-operator/pkg/agent       12.611s coverage: 72.6% of statements
ok      github.com/stolostron/hypershift-addon-operator/pkg/install     175.495s        coverage: 86.0% of statements
ok      github.com/stolostron/hypershift-addon-operator/pkg/manager     120.051s        coverage: 60.2% of statements
ok      github.com/stolostron/hypershift-addon-operator/pkg/metrics     0.007s  coverage: 100.0% of statements
? …
```

ACM-3429 Add retry to get mce csv when upgrading

---

pkg/manager/manager.go
pkg/manager/manifests/permission/clusterrolebinding.yaml

* A cluster role binding with the same name is attempted to be created for each managed cluster that the hypershift addon is installed on. The binding fails to create, causing the managed cluster to fail to delete due to lack of permission. This change creates a different cluster role binding for each managed cluster the HC addon is installed on. The ideal way is to have one binding and includes the groups for all the managed clusters but the addon registration does not support updating the binding.
*  Managed clusters, other than local-cluster, are not being deleted when the HC is deleted. The delete fails due to lack of permission.
* https://issues.redhat.com/browse/ACM-2094
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	30.031s	coverage: 71.3% of statements
ok …
```

HyperShift cluster role binding not created for managed clusters

---

Makefile
hack/install_ocm.sh

* Fix e2e by downloading and running the clusteradm binary instead of building it from source
* This project is currently using go 1.18 and the clusteradm project requires 1.19 to build.
* NA
```script
Not applicable - e2e test script changes only
```

Fix e2e by downloading and running the clusteradm binary instead of building it from source

---

test/canary/run_canary_test.sh

* set the priority & severity of foundation test cases
*  CICD needs each canary test case has a name with prefix `[Priority][Severity][squad-github-tag]`, this change will update the foundation test cases name to add the required meta data.
* 
```script
```

set the priority & severity of foundation test cases

---

pkg/agent/agent.go
pkg/agent/external_secret_controller.go
pkg/agent/external_secret_controller_test.go
pkg/manager/manifests/templates/clusterrole.yaml
pkg/util/constant.go

* Reconcile on klusterlet as well
* Controller to trigger HC reconcile
* fixed client, added finalizer steps
* Fix delete finalizer condition, change UpdateFunc
* changed event filter, increased retries
* Removed event filter for now
* Fix vulnerability
* Added tests
* Remove code smell
* Only reconcile on create, use timestamp for annotation
* resolve reviews
* Add coverage
* Remove retry, requeue instead
---------
* 
*  
* 
```script
ok      github.com/stolostron/hypershift-addon-operator/pkg/agent       15.031s coverage: 71.3% of statements
ok      github.com/stolostron/hypershift-addon-operator/pkg/install     175.632s        coverage: 86.0% of statements
ok …
```

[Cherrypick] ACM-2180 Reconcile on klusterlet as well (#237)

---

pkg/agent/external_secret_controller.go

The HypershiftAddonOperator is using an outdated version of the HostedCluster API. The result is when this controller performs an `Update` on a HC, some new fields get dropped that this controller has no knowledge of.
One way to prevent this moving forward is to always use a Patch operation on objects owned by other controllers (like the HostedCluster object).
```script
```

Use Patch instead of Update for HostedCluster Objects

---

pkg/manager/cli_download_install.go

* Add downloadable Power and Z hypershift CLI binaries
*  Add downloadable Power and Z hypershift CLI binaries
* https://issues.redhat.com/browse/ACM-6535
```script
KUBEBUILDER_ASSETS="/Users/rokej/Library/Application Support/io.kubebuilder.envtest/k8s/1.22.1-darwin-amd64" go test github.com/stolostron/hypershift-addon-operator/cmd github.com/stolostron/hypershift-addon-operator/pkg/agent github.com/stolostron/hypershift-addon-operator/pkg/install github.com/stolostron/hypershift-addon-operator/pkg/manager github.com/stolostron/hypershift-addon-operator/pkg/metrics github.com/stolostron/hypershift-addon-operator/pkg/util -coverprofile cover.out
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	31.213s …
```

add Power and Z CLI binaries

---

pkg/agent/auto_import_controller.go
pkg/agent/external_secret_controller_test.go
pkg/install/hypershift.go
pkg/install/hypershift_test.go
pkg/install/upgrade_test.go

This PR enables the optional defaulting webhook for the hypershift operator. This webhook is used by self managed Hypershift in order to dynamically set the release image to the latest supported release image for the current hypershift operator. The webhook will likely continue to be enhanced to support any sort of dynamic defaulting that we can't express accurately on the CRD using CEL..
*  Some defaulting, such as defaulting the release image, can not be expressed accurately on the CRD's API using CEL. For this defaulting, we have created a webhook to inject the defaults at HostedCluster/NodePool creation time.
* https://issues.redhat.com/browse/HOSTEDCP-1041 
* https://github.com/openshift/hypershift/pull/2892
```script
```

[HOSTEDCP-1041] Enable defaulting webhook for hypershift operator with self managed

---

pkg/agent/auto_import_controller.go
pkg/agent/auto_import_controller_test.go

* Find ACM operator in any namespace
*  The auto-import controller currently looks for ACM operator named `advanced-cluster-management.open-cluster-management` assuming that it is installed in `open-cluster-management` namespace to determine whether to enable ACM addons. Users can install the ACM operator in any namespace which changes the operator name to `advanced-cluster-management.xyz`. 
* https://issues.redhat.com/browse/ACM-6917
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	30.846s	coverage: 72.0% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	176.357s	coverage: 86.1% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/manager …
```

detect ACM operator in any namespace

---

go.mod
go.sum
pkg/agent/addon_status_controller.go
pkg/agent/agent.go
pkg/agent/agent_test.go

* When the addon agent starts up the very first time, the Degraded type condition should be True indicating there is no successful hypershift operator installation yet.
*  Until the hypershift operator is deployed, there is no status condition to indicate whether the HO is running. 
* https://issues.redhat.com/browse/ACM-6988
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	25.799s	coverage: 71.6% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	176.295s	coverage: 86.1% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/manager	120.791s	coverage: 61.7% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/metrics	0.542s …
```

Initially the addon status should contain HO degraded true

---

pkg/agent/auto_import_controller.go
pkg/agent/auto_import_controller_test.go

* Set `open-cluster-management/created-via: hypershift` annotation when the hypershift agent auto-imports a hosted cluster.
*  So we can collect telemetry data on the usage of MCE hypershift to provision OCP hosted clusters.
* https://issues.redhat.com/browse/ACM-6547
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	33.027s	coverage: 71.7% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	176.466s	coverage: 86.1% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/manager	121.613s	coverage: 61.7% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/metrics	0.454s	coverage: 100.0% of statements
? …
```

set created-via annotation to hypershift

---

docs/installing_hypershift_cli.md
pkg/manager/cli_download_install.go
pkg/manager/cli_download_install_test.go
pkg/manager/manifests/cli/consoledownload.yaml
pkg/manager/manifests/cli/deployment.yaml
pkg/manager/manifests/cli/route.yaml
pkg/manager/manifests/cli/service.yaml

* Switch to making productized `hcp cli` downloadable
*  We want MCE and ACM users to use the `hcp cli` instead of the internal-dev `hypershift cli`. 
* https://issues.redhat.com/browse/ACM-6105
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	31.249s	coverage: 71.9% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	176.186s	coverage: 86.1% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/manager	121.269s	coverage: 61.7% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/metrics	1.111s	coverage: 100.0% of statements
```

make productized hcp CLI binaries downloadable

---

pkg/manager/manifests/templates/metrics-clusterrole.yaml
pkg/manager/manifests/templates/metrics-clusterrolebinging.yaml

* Adds RBAC rule in the cluster role binding for the kube proxy container.
*  To fix the following authorization error
```
E0905 19:26:47.931331       1 proxy.go:96] Authorization error (user=system:serviceaccount:openshift-monitoring:prometheus-k8s, verb=get, resource=, subresource=): subjectaccessreviews.authorization.k8s.io is forbidden: User "system:serviceaccount:open-cluster-management-agent-addon:hypershift-addon-agent-sa" cannot create resource "subjectaccessreviews" in API group "authorization.k8s.io" at the cluster scope
I0905 19:27:01.045017       1 round_trippers.go:443] POST [https://172.30.0.1:443/apis/authorization.k8s.io/v1/subjectaccessreviews](https://172.30.0.1/apis/authorization.k8s.io/v1/subjectaccessreviews) 403 Forbidden in 1 milliseconds
E0905 19:27:01.045132 …
```

ACM-7330: fixing authorization error in kube proxy container

---

pkg/manager/cli_download_install.go
pkg/manager/cli_download_install_test.go

* When MCE with hypershift-preview feature enabled is upgraded, the old hypershift CLI download resources (deployment, service, route and ConsoleCLIDownload) with name `hypershift-cli-download` remain while the new resources with new name `hcp-cli-download` are created.
*  The old resources are unnecessary and need to be removed on MCE upgrade.
* https://issues.redhat.com/browse/ACM-7280
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	35.179s	coverage: 71.7% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	176.458s	coverage: 86.1% of statements
ok …
```

ACM-7280: remove old CLI download resources

---

pkg/install/hypershift.go
pkg/install/hypershift_test.go
pkg/install/upgrade_test.go

* Add the `--enable-validating-webhook` flag the installation of a self managed hypershift
*  This PR enables the optional validating webhook for the hypershift operator. This webhook is used by self managed Hypershift in order to validate the make sure the selected openshift-virtualization infrastructure cluster is with sufficient kubernetes and openshift virtualization versions.
* CNV-34094
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	12.338s	coverage: 71.9% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	175.531s	coverage: 86.1% of statements
ok …
```

[CNV-34094] Enable validating webhook for hypershift operator with self managed

---

pkg/install/install_job.go
pkg/manager/manifests/templates/deployment.yaml

*  To ensure that the Pod runs with the 'readonlyrootfilesystem' and 'privileged' settings
*  In order to enhance the security and functionality of our application.
* https://issues.redhat.com/browse/ACM-8466
```script
KUBEBUILDER_ASSETS="/Users/rokej/Library/Application Support/io.kubebuilder.envtest/k8s/1.22.1-darwin-amd64" go test github.com/stolostron/hypershift-addon-operator/cmd github.com/stolostron/hypershift-addon-operator/pkg/agent github.com/stolostron/hypershift-addon-operator/pkg/install github.com/stolostron/hypershift-addon-operator/pkg/manager github.com/stolostron/hypershift-addon-operator/pkg/metrics github.com/stolostron/hypershift-addon-operator/pkg/util -coverprofile cover.out
? …
```

ACM-8466: Set container SCC

---

pkg/manager/manifests/templates/clusterrole.yaml

* Allow hypershift-addon-agent SA access to `validatingwebhookconfigurations.admissionregistration.k8s.io`.
*  A recent hypershift operator 4.15 started to create a `validatingwebhookconfigurations.admissionregistration.k8s.io` resource as part of the HO installation and the install user hypershift-addon-agent SA does not have role permission to create that. This PR is to fix the hypershift operator installation error due to this lack of RBAC.
* https://issues.redhat.com/browse/ACM-9229
```script
N/A
```

ACM-9229: fix HO installation issue

---

docs/cluster_capacity_metrics_hcp.md
pkg/agent/agent.go
pkg/agent/agent_test.go
pkg/agent/hcp_capacity_calculation.go
pkg/agent/hcp_capacity_calculation_test.go
pkg/util/constant.go

* The hypershift addon agent calculates the cluster capacity for hosting HCPs based on some default resource utilization values documented in https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/clusters/cluster_mce_overview#hosted-sizing-guidance. However, there will be a case where these baseline values can be different. 
*  Users can override the default HCP utilization measurements via a special configmap so that the agent can generate more accurate metrics on the cluster's capacity to host HCPs.
* 
```script
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	29.414s …
```

HCP sizing calculation baseline override

---

pkg/agent/agent.go
pkg/agent/hcp_capacity_calculation.go

* During the hypershift addon agent startup, the Hypershift operator has not been installed yet. Therefore, the HCP capacity calculation that tries to query the number of HostedControlPlane fails. The agent should be able to continue the calculation assuming there is zero HostedControlPlane in this case.
*  We need this fix for the agent to be able to calculate how many HCPs the cluster can host during the agent startup time when the hypershift operator is absent in the cluster.
* https://issues.redhat.com/browse/ACM-9269
```script
```

ACM-9269: fix HCP capacity calculation during the agent startup

---

pkg/agent/agent.go
pkg/agent/hcp_capacity_calculation.go

* There could be situations where initializing the Prometheus API client can fail due to environment problems. The client is used to query and calculate the average KubeAPI QPS by all HCPs in the cluster and use it to calculate the cluster's capacity for hosting HCPs. Today, the agent fails to start if it fails to create this client.
*  The prometheus client and the average KubeAPI QPS by all HCPs is not mandatory for the agent. Report the unavailability of the client in the log and let the agent continue to start.
* https://issues.redhat.com/browse/ACM-9278
```script
```

ACM-9278: Graceful prometheus client init failure

---

pkg/manager/manifests/templates/clusterrole.yaml

Allow hypershift addon access to scheduling.hypershift.openshift.io. This is related to work done in [HOSTEDCP-1429](https://issues.redhat.com//browse/HOSTEDCP-1429).

HOSTEDCP-1429: Allow hypershift addon access to scheduling.hypershift.openshift.io

---

test/canary/run_canary_test.sh

* fix canary test to use no-cgo hypershift CLI
*  
* https://github.com/stolostron/backlog/issues/27571
```script
```

fix canary to use no-cgo hypershift CLI

---

pkg/manager/manifests/permission/role.yaml

* Updated the RBAC verbs on `DiscoveredClusters` resources for managed cluster namespaces to match the RBAC verbs that the hypershift addon manager allows.
*  
* https://issues.redhat.com/browse/ACM-11604
```script
```

ACM-11604: Fixed RBAC verbs on managed cluster namespace

---

pkg/agent/agent.go
pkg/agent/agent_suite_test.go
pkg/agent/auto_import_controller.go
pkg/agent/auto_import_controller_test.go
pkg/agent/discovery_agent.go
pkg/install/upgrade.go
pkg/manager/manifests/templates/deployment.yaml

* This change is to support running two copies of hypershift addon agent in an MCE cluster. One agent is deployed for MCE local-cluster responsible for everything it normally does. The other agent is deployed by ACM mainly as a HCP discovery agent who is responsible to discover hosted clusters from MCE and manage corresponding DiscoveredCluster resources in ACM hub for auto-import. This discovery agent should not do any duplicate work such as generating metrics data and managing the hypershift operator.
*  We need this PR so ACM can deploy the hypershift addon agent as a HCP discovery agent for MCE clusters.
* https://issues.redhat.com/browse/ACM-11298
```script
```

ACM-11298: local-cluster hypershift addon agent co-exists with managed agent

---

pkg/manager/manager.go

* Make the hypershift addon agent install namespace to be configurable via a addonDeploymentConfig. 
*  This allows the hypershift addon to be enabled for the same managed cluster by multiple hub clusters (multiple hypershift addon agents in different namespaces in a managed cluster).
* https://issues.redhat.com/browse/ACM-11332
```script
```

ACM-11332: Support non-default agent install namespace

---

pkg/agent/agent.go
pkg/agent/external_secret_controller.go
pkg/agent/external_secret_controller_test.go

* Fixed the external secret controller to handle a klusterlet for a discovered hosted cluster from ACM
*  In order to auto-import a MCE discovered hosted cluster into ACM
* https://issues.redhat.com/browse/ACM-11298
```script
```

ACM-11298: Fixed external secret controller for discovery

---

pkg/agent/auto_import_controller_test.go
pkg/agent/discovery_agent.go
pkg/agent/discovery_agent_test.go

* Use hosted cluster's cluster ID as discovered cluster's `spec.name` and `metadata.name` 
*  
* https://issues.redhat.com/browse/ACM-11977
```script
```

ACM-11977: Use HC cluster ID as DiscoverdCluster name

---

docs/discovering_hostedclusters.md
pkg/manager/cli_download_install.go
pkg/manager/cli_download_install_test.go
pkg/manager/manifests/cli/deployment.yaml

* MCE installation could be configured with additional tolerations to be installed on specific nodes. When the hypershift addon manager programatically installs the hcp CLI download deployment, the CLI deployment should inherit the tolerations from the adddon manager.
*  Without this change, MCE installation will be stuck.
* https://issues.redhat.com/browse/ACM-11310
```script
```

ACM-11310: Set hcp cli deployment with the same tolerations 

---

pkg/agent/auto_import_controller.go
pkg/agent/auto_import_controller_test.go

This change allows users who are creating HostedClusters to place labels on the hosted cluster which are then synced to the ManagedCluster during the auto import stage. 
By syncing the labels from the HC to the MC, it allows people to influence what addons are installed into the HCP cluster when creating the HCP from the `hcp` cli tool. 
Related to https://github.com/openshift/hypershift/pull/4451
```script
$ make test
which: no clusteradm in (/home/dvossel/.krew/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/dvossel/.local/bin:/home/dvossel/bin:/bin:/home/dvossel/go/bin:/home/dvossel/go/bin)
go fmt ./...
go vet ./...
KUBEBUILDER_ASSETS="/home/dvossel/.local/share/kubebuilder-envtest/k8s/1.22.1-linux-amd64" go test …
```

Sync labels to mc

---

pkg/agent/agent.go
pkg/agent/agent_helper.go
pkg/agent/agent_helper_test.go
pkg/agent/agent_suite_test.go
pkg/agent/auto_import_controller.go
pkg/agent/auto_import_controller_test.go
pkg/agent/discovery_agent.go
pkg/agent/external_secret_controller.go

* The hypershift addon agent makes some decisions based on whether the agent is for the local cluster or not by checking the hard-coded cluster name `local-cluster`. This PR is to remove the hard-coded local cluster name `local-cluster` and use the `local-cluster=true` label in a ManagedCluster CR to determine the name of the local cluster.
*  
* https://issues.redhat.com/browse/ACM-13163
```script
```

ACM-13163: Remove hard-coded local-cluster

---

pkg/manager/cli_download_install.go

* The hypershift addon manager code was updated to delete and re-create, if already exists, the hcp-cli-download deployment when the manger starts up.
*  In order to ensure that the hcp-cli-download gets upgraded when MCE is upgraded.
* https://issues.redhat.com/browse/ACM-12995
```script
```

ACM-12995: Fix hcp cli upgrade

---

docs/advanced/provision_hypershift_clusters_by_manifestwork.md
pkg/manager/cli_download_install.go
pkg/manager/cli_download_install_test.go
quickstart/start.sh
test/canary/run_canary_test.sh

* Removing `-preview` from the hypershift addon chart in https://github.com/stolostron/backplane-operator/pull/990 removed `-preview` from some addon resource names. This broke the code that looks for these resources to enable the hcp cli download. 
*  
* https://issues.redhat.com/browse/ACM-14690
```script
github.com/stolostron/hypershift-addon-operator/cmd		coverage: 0.0% of statements
github.com/stolostron/hypershift-addon-operator/pkg/util		coverage: 0.0% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	54.128s	coverage: 69.6% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	176.774s	coverage: 85.0% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/manager	128.927s	coverage: 60.1% of statements
ok …
```

ACM-14690: HCP CLI download fix

---

docs/discovering_hostedclusters.md
go.mod
go.sum
pkg/agent/agent.go
pkg/agent/discovery_agent.go
pkg/agent/discovery_agent_test.go
pkg/manager/manifests/templates/deployment.yaml

* This PR allows users to configure the prefix for discovered hosted cluster names.
*  Discovered hosted clusters are auto-imported with [hosting-cluster-name]-[hosted-cluster-name] naming convention but some users do not want the `[hosting-cluster-name]-` prefix because hosted clusters across the fleet have unique names, etc. 
* https://issues.redhat.com/browse/ACM-15500
```script
github.com/stolostron/hypershift-addon-operator/cmd		coverage: 0.0% of statements
github.com/stolostron/hypershift-addon-operator/pkg/util		coverage: 0.0% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	54.440s	coverage: 69.1% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install	176.213s	coverage: 85.0% of statements
ok …
```

ACM-15500: configuring name prefix of discovered hcps

---

pkg/agent/agent.go
pkg/agent/auto_import_controller.go
pkg/agent/discovery_agent.go
pkg/metrics/hosted-clusters-metrics.go

```
mce_hcp_ext_managed_kubeconfig_ts_gauge{hcp_name="virt-4", infra_id="virt-4"}
```
mce_hcp_api_server_avail_ts_gauge{hcp_name="virt-4", infra_id="virt-4"}
* https://issues.redhat.com/browse/ACM-15551
```script
```

ACM-15551: Add creation timestamp metrics

---

pkg/agent/agent.go
pkg/agent/auto_import_controller.go
pkg/agent/discovery_agent.go
pkg/metrics/hosted-clusters-metrics.go

_mce_hcp_ext_managed_kubeconfig_ts_gauge{hcp_name="virt-4", infra_id="virt-4"}_
_mce_hcp_api_server_avail_ts_gauge{hcp_name="virt-4", infra_id="virt-4"}_
* https://issues.redhat.com/browse/ACM-15978
```script
```

ACM-15978: Add creation timestamp metrics

---

pkg/agent/agent.go
pkg/agent/auto_import_controller.go
pkg/agent/discovery_agent.go
pkg/metrics/hosted-clusters-metrics.go

_mce_hcp_ext_managed_kubeconfig_ts_gauge{hcp_name="virt-4", infra_id="virt-4"}_
_mce_hcp_api_server_avail_ts_gauge{hcp_name="virt-4", infra_id="virt-4"}_
* https://issues.redhat.com/browse/ACM-15979
```script
```

ACM-15979: add hcp timestamp metrics

---

pkg/agent/agent.go
pkg/metrics/hosted-clusters-metrics.go

_mce_hcp_ext_managed_kubeconfig_ts_gauge{hcp_name="virt-4", infra_id="virt-4"}_
_mce_hcp_api_server_avail_ts_gauge{hcp_name="virt-4", infra_id="virt-4"}_
* https://issues.redhat.com/browse/ACM-15980
* 
```script
```

ACM-15980: add hcp timestamp metrics

---

pkg/agent/agent.go
pkg/metrics/hosted-clusters-metrics.go

_mce_hcp_ext_managed_kubeconfig_ts_gauge{hcp_name="virt-4", infra_id="virt-4"}_
_mce_hcp_api_server_avail_ts_gauge{hcp_name="virt-4", infra_id="virt-4"}_
* https://issues.redhat.com/browse/ACM-15992
* 
```script
```

ACM-15992: add hcp timestamp metrics

---

docs/advanced/running_mce_acm_addons_hostedmode.md
docs/discovering_hostedclusters.md
docs/provision_hosted_cluster_on_mce_local_cluster.md
pkg/agent/auto_import_controller.go

* Added missing ManagedCluster vendor and cloud auto-detect labels
*  Some custom or ACM logics might depend on auto-detected vendor and cloud.
* https://issues.redhat.com/browse/ACM-16840
```script
```

ACM-16840: added missing ManagedCluster auto-detect labels

---

docs/advanced/running_mce_acm_addons_hostedmode.md
docs/discovering_hostedclusters.md
docs/provision_hosted_cluster_on_mce_local_cluster.md
pkg/agent/auto_import_controller.go

* Added missing ManagedCluster vendor and cloud auto-detect labels
*  Some custom or ACM logics might depend on auto-detected vendor and cloud.
* https://issues.redhat.com/browse/ACM-16840
```script
```

ACM-16840: added missing ManagedCluster auto-detect labels (#384)

---

pkg/agent/agent.go

* The agent copies the hosted cluster's kubeadmin password and kubeconfig secrets to the hub cluster. When OAuth is configured in the hosted cluster, the hypershift operator deletes the kubeadmin password secret from the hosted cluster but the mirrored kubeadmin password secret that the agent initially copied over to the hub remains in the hub. This change ensures that the secret gets deleted or re-created depending on the OAuth configuration in the hosted cluster.
*  
* https://issues.redhat.com/browse/ACM-17572
```script
```

ACM-17106: fix the management of mirrored admin secrets (#389)

---

pkg/agent/agent.go

* The agent does not properly update the external-managed-kubeconfig secret data.
*  When a hosted cluster's KAS cert is rotated, the kubeconfig data in the external-managed-kubeconfig secret becomes invalid. This causes the klusterlet agents to loose connection and become unhealthy.
* https://issues.redhat.com/browse/ACM-17829
```script
```

ACM-17667: update external-managed-kubeconfig correctly (#395)

---

pkg/agent/agent.go
pkg/agent/auto_import_controller.go
pkg/agent/auto_import_controller_test.go
pkg/agent/discovery_agent.go
pkg/agent/discovery_agent_test.go
pkg/agent/external_secret_controller.go
pkg/agent/hcp_kubeconfig_watcher.go
pkg/agent/hcp_kubeconfig_watcher_test.go
pkg/agent/suite_test.go

* This optimizes the agent's reconciliation rate by filtering out unimportant HostedCluster resource events. This change reduces the number of reconciliations by 82% percent per hosted cluster. 
*  When there are a large number of hosted clusters, the resource events can create a bottleneck in the agent controller's reconciliation queue causing some of the important events to be lost in the queue. 
* https://issues.redhat.com/browse/ACM-15162
```script
github.com/stolostron/hypershift-addon-operator/cmd		coverage: 0.0% of statements
github.com/stolostron/hypershift-addon-operator/pkg/util		coverage: 0.0% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	67.027s	coverage: 70.1% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install …
```

ACM-15162: optimize the agent reconciliation rate

---

pkg/agent/agent.go
pkg/agent/auto_import_controller.go
pkg/agent/auto_import_controller_test.go
pkg/agent/discovery_agent.go
pkg/agent/discovery_agent_test.go
pkg/agent/external_secret_controller.go
pkg/agent/hcp_kubeconfig_watcher.go
pkg/agent/hcp_kubeconfig_watcher_test.go
pkg/agent/suite_test.go

* This optimizes the agent's reconciliation rate by filtering out unimportant HostedCluster resource events. This change reduces the number of reconciliations by 82% percent per hosted cluster. 
*  When there are a large number of hosted clusters, the resource events can create a bottleneck in the agent controller's reconciliation queue causing some of the important events to be lost in the queue. 
* https://issues.redhat.com/browse/ACM-18286
```script
github.com/stolostron/hypershift-addon-operator/cmd		coverage: 0.0% of statements
github.com/stolostron/hypershift-addon-operator/pkg/util		coverage: 0.0% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/agent	67.027s	coverage: 70.1% of statements
ok  	github.com/stolostron/hypershift-addon-operator/pkg/install …
```

ACM-15162: optimize the agent reconciliation rate (#410)

---

docs/hosting_cluster_topologies.md
pkg/manager/manifests/templates/deployment.yaml

* the topology described in https://github.com/stolostron/hypershift-addon-operator/blob/main/docs/hosting_cluster_topologies.md#mce-managed-aka-spoke-leaf-ocp-cluster-as-a-hosting-cluster does not work.  This is due to a mismatch between the environment variable name set in the YAML template and the code that controls the flow.
*  To fix the auto-import of hosted clusters from a managed cluster.
* https://issues.redhat.com/browse/ACM-18678
```script
```

ACM-18678: fix the auto-import of managed cluster's hosted cluster

---

go.mod
go.sum

* Upgraded go module github.com/golang-jwt/jwt/v5 to v5.2.2
* https://issues.redhat.com/browse/ACM-19213
```script
```

ACM-19213 CVE-2025-30204

---

go.mod
go.sum

* Upgraded go module github.com/golang-jwt/jwt/v5 to v5.2.2
* https://issues.redhat.com/browse/ACM-19215
```script
```

ACM-19215 CVE-2025-30204

---

go.mod
go.sum

* Upgraded go module github.com/golang-jwt/jwt/v5 to v5.2.2
* https://issues.redhat.com/browse/ACM-19214
```script
```

ACM-19214 CVE-2025-30204

---

go.mod
go.sum

* Upgraded go module github.com/golang-jwt/jwt/v4 to v4.5.2
* https://issues.redhat.com/browse/ACM-19211
```script
```

ACM-19211 CVE-2025-30204

---

go.mod
go.sum

* Upgraded go module github.com/golang-jwt/jwt/v4 to v4.5.2
* https://issues.redhat.com/browse/ACM-19212
```script
```

ACM-19212 CVE-2025-30204

---

go.mod
go.sum

A recent bug might impact hypershift users, refer to https://github.com/open-cluster-management-io/addon-framework/pull/298.
Create this PR to upgrade the addon-framework. 
Depends on PR https://github.com/open-cluster-management-io/addon-framework/pull/299. 
The bug in the addon-framework affects the manually created ManagedClusterAddon with AddonDeploymentConfigs, and it seems the hypershift mca is not created automatically so the users might be affected.
https://github.com/stolostron/hypershift-addon-operator/pull/401
```script
```

[backplane-2.6] upgrade addon-framework to v0.9 latest
